#!/usr/bin/env bash
# Verify that docs/ is what viewer/ currently compiles to.
#
#   scripts/check-pages-fresh.sh
#
# docs/viewer is generated by build-pages.sh and committed, so it can silently
# fall out of step with its source in two different ways. They need two
# different checks, because the obvious one only catches the first:
#
#   1. Someone edits viewer/ and does not re-run build-pages.sh. The committed
#      hosted page then lags the source, and the live demo runs code nobody is
#      testing — the viewer tests exercise viewer/index.html, not the copy that
#      is actually served. Caught by regenerating and diffing.
#
#   2. CHROMAPAKZ_VERSION drifts from the dependency in package.json. Regenerating
#      does *not* catch this: the script hardcodes the version, so a stale pin
#      reproduces itself byte for byte and the diff stays empty. It has to be
#      compared against package.json directly.
#
# (2) is not hypothetical. The pin sat at 0.8.0 while package.json asked for
# ^0.9.0, so the published demo ran a decoder a minor older than the one every
# test used, and nothing said a word.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

fail=0

# --- 1. the pin matches the declared dependency ------------------------------
pinned="$(sed -n 's/^CHROMAPAKZ_VERSION="\(.*\)"$/\1/p' scripts/build-pages.sh)"
declared="$(node -p "require('./package.json').devDependencies.chromapakz" | tr -d '^~')"

if [ -z "$pinned" ]; then
  echo "error: could not read CHROMAPAKZ_VERSION from scripts/build-pages.sh" >&2
  fail=1
elif [ "$pinned" != "$declared" ]; then
  echo "error: the hosted viewer pins chromapakz $pinned but package.json declares $declared." >&2
  echo "       The published demo would run a different decoder than the tests." >&2
  echo "       Update CHROMAPAKZ_VERSION in scripts/build-pages.sh and re-run it." >&2
  fail=1
else
  echo "ok: hosted viewer pins chromapakz $pinned, matching package.json"
fi

# --- 2. docs/ is what viewer/ regenerates to ---------------------------------
#
# The comparison is working tree vs. freshly generated, NOT vs. git HEAD. Diffing
# against HEAD conflates two different things: "docs/ does not match its source"
# (what we care about) and "docs/ has been regenerated but not committed yet"
# (the normal edit-then-commit flow, which is fine). An earlier version made that
# mistake and, worse, ran `git checkout -- docs/` to tidy up — which discards a
# correct regeneration the caller had just made.
snapshot="$(mktemp -d)"
trap 'rm -rf "$snapshot"' EXIT
cp -R docs/viewer "$snapshot/viewer"

scripts/build-pages.sh >/dev/null

if ! diff -r -q "$snapshot/viewer" docs/viewer >/dev/null 2>&1; then
  echo "error: docs/ is stale — regenerating it changed these files:" >&2
  diff -r -q "$snapshot/viewer" docs/viewer 2>&1 | sed 's/^/       /' >&2
  echo "       Run scripts/build-pages.sh and commit the result." >&2
  # Put back exactly what was there; never reach for git, which cannot tell a
  # stale file from an uncommitted-but-correct one.
  rm -rf docs/viewer && cp -R "$snapshot/viewer" docs/viewer
  fail=1
else
  echo "ok: docs/ matches what viewer/ generates"
fi

exit "$fail"
